### ISSUE TITLE
FileIO

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaDB/CSV.jl#1]
Hi,
from what I read on julia-users and the CSV issue, you seem to be onto a very fast pattern for parsing files!
Do you think, that your approach will be applicable for parsing other file formats?
If so, it would be great to share your file and string types/methods with other IO libraries, probably by putting them into [FileIO.jl](https://github.com/JuliaIO/FileIO.jl) or some generic file parser library.
It seems like what you came up with is also great for just parsing parts of the file, and editing the file while updating the parsed julia type (or the other way around).
Would be great to have this speed and functionality as a default for all Julia IO libraries.

@sjkelly maybe we can learn a thing or two for MeshIO.

Best,
Simon

**Comment by quinnj** [comment]
Hey Simon, I definitely feel like I learned a lot in the process of creating CSV.jl. You'll be at JuliaCon, right? I think we should do a larger discussion with everyone on a plan forward for FileIO.jl. I think there's great potential for the idea and we just need some more consensus/momentum behind it.

**Comment by quinnj** [comment]
Happy to share any insights or answer other questions if needed.

**Comment by SimonDanisch** [comment]
Sounds like a good plan!
Looking forward to JuliaCon :)

2015-06-09 3:29 GMT+02:00 Jacob Quinn <notifications@github.com>:
