### ISSUE TITLE
Reading strings into DataFrame produces strange result

### ISSUE THREAD

**Issue by davidanthoff** [JuliaDB/CSV.jl#21]
When I read a csv file into a DataFrame like this:
````julia
df = DataFrame(CSV.csv("filename.csv"))
````
and that file has string columns, they end up showing as ``"#undef"`` when I show the DataFrame on the REPL. Probably because the type of a string column in the DataFrame ends up as ``DataArray{DataStreams.Data.PointerString{T},1}``? Could those actually end up as a normal ``UTF8String`` in the DataFrame?

**Comment by quinnj** [comment]
There have been a slew of updates in various packages, but CSV.jl now returns a DataFrame as the return type of `CSV.csv` (which is now renames `CSV.read`).
