### ISSUE TITLE
"Lazy" read a CSV?

### ISSUE THREAD

**Issue by quinnj** [JuliaDB/CSV.jl#4]
I wonder about the potential use/worth of a "lazily" read CSV file. My idea here is:

* "reading" a CSV file would mainly involve constructing a `CSV.File` (with all properties set), storing a reference to the file's mmap, and going through and figuring out all the field offsets
* The resulting type (let's call it a `CSV.Table`, would have various indexing operations defined to "use" it, but all the actual value parsing would be delayed until physical access of those values. If a column was never accessed, its values would never actually be parsed.

My hope is that this would potentially allow an extremely fast "parsing" experience with some of the cost deferred until actual values are needed.

The actual implementation may be tricky to sort out exactly how to tell if a value has been parsed or not, but that's a separate concern.

@johnmyleswhite

**Comment by johnmyleswhite** [comment]
I think this is potentially useful, but it requires a lot of memory, so there are still contexts in which it's not useful (e.g. streaming). For other contexts, it would be good to know how it impacts final performance.

FWIW, DataFrames already does something like this: the initial read through the file only locates field offsets.
